# -*- coding: utf-8 -*-
"""Data_ pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CkOFt6JGiyKPguF4vZEkYbe3ULmWInF9

Books to Scrape
      ↓
Scrape first 5 catalogue pages
      ↓
100 books collected
      ↓
Select 60 books from at least 3 categories
      ↓
Clean price, rating, availability
      ↓
Calculate price_inr = price_gbp × 105.50
      ↓
Create SQLite database
      ↓
Run 5 SQL queries
      ↓
Read results using pd.read_sql()
      ↓
Reproduce JOIN using pd.merge()
      ↓
Compare both results
"""

pip install requests beautifulsoup4 pandas

import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import sqlite3
import os
from urllib.parse import urljoin
from IPython.display import display

BASE_URL = "https://books.toscrape.com/"
ALL_PRODUCTS_URL = "https://books.toscrape.com/catalogue/page-{}.html"

EXCHANGE_RATE = 105.50

REQUIRED_BOOKS = 60
PAGES_TO_SCRAPE = 5

DB_NAME = "books.db"

print("Setup completed successfully.")

def get_soup(url):
    response = requests.get(url, timeout=30)
    response.raise_for_status()
    return BeautifulSoup(response.text, "html.parser")

print("get_soup function ready.")

# ============================================================
# SCRAPE EXACTLY 3 CATEGORIES
# 20 BOOKS FROM EACH CATEGORY = 60 BOOKS
# ============================================================

from urllib.parse import urljoin
import pandas as pd

TARGET_CATEGORIES = [
    "Mystery",
    "Historical Fiction",
    "Fantasy"
]

BOOKS_PER_CATEGORY = 20


def get_category_urls():
    """
    Find the URLs of the required categories from the website.
    """

    homepage_url = "https://books.toscrape.com/index.html"

    soup = get_soup(homepage_url)

    category_urls = {}

    # Category links are inside the navigation list
    category_links = soup.select("ul.nav-list ul li a")

    for link in category_links:

        category_name = link.get_text(strip=True)

        if category_name in TARGET_CATEGORIES:

            category_url = urljoin(
                homepage_url,
                link.get("href")
            )

            category_urls[category_name] = category_url

    return category_urls


def scrape_category(category_name, category_url):
    """
    Scrape books from one category until 20 unique books
    are collected.
    """

    books = []

    page_url = category_url

    page_number = 1

    while page_url and len(books) < BOOKS_PER_CATEGORY:

        print(
            f"Scraping {category_name} - page {page_number}"
        )

        soup = get_soup(page_url)

        products = soup.select("article.product_pod")

        print(
            f"Books found on page: {len(products)}"
        )

        for product in products:

            if len(books) >= BOOKS_PER_CATEGORY:
                break

            # ------------------------------------------------
            # TITLE
            # ------------------------------------------------

            title_element = product.select_one(
                "h3 a"
            )

            title = title_element.get(
                "title"
            )

            # ------------------------------------------------
            # PRICE
            # ------------------------------------------------

            price_element = product.select_one(
                ".price_color"
            )

            price = price_element.get_text(
                strip=True
            )

            # ------------------------------------------------
            # RATING
            # ------------------------------------------------

            rating_element = product.select_one(
                "p.star-rating"
            )

            rating_class = rating_element.get(
                "class"
            )

            star_rating = rating_class[1]

            # ------------------------------------------------
            # AVAILABILITY
            # ------------------------------------------------

            availability_element = product.select_one(
                ".availability"
            )

            availability = availability_element.get_text(
                " ",
                strip=True
            )

            # ------------------------------------------------
            # BOOK URL
            # ------------------------------------------------

            relative_url = title_element.get(
                "href"
            )

            book_url = urljoin(
                page_url,
                relative_url
            )

            # ------------------------------------------------
            # DETAIL PAGE
            # ------------------------------------------------

            book_soup = get_soup(book_url)

            # Breadcrumb is not needed for category because
            # we already know the category being scraped.
            # We explicitly assign the target category here.

            books.append({
                "title": title,
                "price": price,
                "star_rating": star_rating,
                "availability": availability,
                "category": category_name,
                "book_url": book_url
            })

        # ----------------------------------------------------
        # NEXT PAGE
        # ----------------------------------------------------

        next_link = soup.select_one(
            "li.next a"
        )

        if next_link and len(books) < BOOKS_PER_CATEGORY:

            page_url = urljoin(
                page_url,
                next_link.get("href")
            )

            page_number += 1

        else:

            page_url = None

    return books


print("Category scraper is ready.")

def scrape_all_products():

    books = []

    for page_number in range(1, PAGES_TO_SCRAPE + 1):

        page_url = ALL_PRODUCTS_URL.format(page_number)

        print(f"Scraping catalogue page: {page_number}")

        soup = get_soup(page_url)

        products = soup.select("article.product_pod")

        print(f"Books found: {len(products)}")

        for product in products:

            # Title
            title = product.h3.a.get("title")

            # Price
            price = product.select_one(
                ".price_color"
            ).get_text(strip=True)

            # Rating
            rating_element = product.select_one(
                "p.star-rating"
            )

            star_rating = rating_element.get("class")[1]

            # Availability
            availability = product.select_one(
                ".availability"
            ).get_text(" ", strip=True)

            # Book URL
            book_url = urljoin(
                page_url,
                product.h3.a.get("href")
            )

            # Detail page
            book_soup = get_soup(book_url)

            breadcrumb = book_soup.select(
                "ul.breadcrumb li a"
            )

            category = breadcrumb[-1].get_text(strip=True)

            books.append({
                "title": title,
                "price": price,
                "star_rating": star_rating,
                "availability": availability,
                "category": category
            })

    return books

print("Scraping function ready.")

# Scrape exactly 60 books from 3 categories

import pandas as pd

category_urls = get_category_urls()

all_books = []

for category in TARGET_CATEGORIES:

    print(f"\nScraping {category}...")

    category_books = scrape_category(
        category,
        category_urls[category]
    )

    # Check sufficient books were collected
    if len(category_books) < 20:
        raise ValueError(
            f"{category} has only "
            f"{len(category_books)} books"
        )

    all_books.extend(category_books[:20])

# Create dataframe
raw_df = pd.DataFrame(all_books)

# Remove duplicate book URLs, if any
raw_df = raw_df.drop_duplicates(
    subset=["book_url"]
).reset_index(drop=True)

# Verify results
print("\nTotal books:", len(raw_df))
print(
    "Total categories:",
    raw_df["category"].nunique()
)

print("\nBooks per category:")
print(raw_df["category"].value_counts())

assert len(raw_df) == 60
assert raw_df["category"].nunique() == 3
assert raw_df["category"].value_counts().eq(20).all()

print("\nSUCCESS: 60 unique books from 3 categories!")

# --------------------------------------------------
# SELECT 60 BOOKS FROM AT LEAST 3 CATEGORIES
# --------------------------------------------------

# Check available categories
print("Available categories:")
print(raw_df["category"].value_counts())

# Select the first 60 books
df = raw_df.head(REQUIRED_BOOKS).copy()

# Check category count
category_count = df["category"].nunique()

print("\nSelected books:", len(df))
print("Number of categories:", category_count)

# Required checks
assert len(df) >= 60, "Dataset contains fewer than 60 books."
assert category_count >= 3, "Dataset contains fewer than 3 categories."

print("\nDataset satisfies the minimum requirement.")

import pandas as pd
import sqlite3

# ============================================================
# CREATE FINAL 60-BOOK DATASET
# 3 ORIGINAL CATEGORIES
# ============================================================

TARGET_CATEGORIES = [
    "Mystery",
    "Historical Fiction",
    "Fantasy"
]

BOOKS_PER_CATEGORY = 20

selected_books = []

for category in TARGET_CATEGORIES:

    category_data = df[
        df["category"] == category
    ].copy()

    print(
        category,
        "available:",
        len(category_data)
    )

    if len(category_data) < 20:
        raise ValueError(
            f"{category} has only "
            f"{len(category_data)} books."
        )

    selected_books.append(
        category_data.head(20)
    )


# Combine exactly 20 from each category
df_60 = pd.concat(
    selected_books,
    ignore_index=True
)


# Remove duplicate books
if "book_url" in df_60.columns:

    df_60 = df_60.drop_duplicates(
        subset=["book_url"]
    ).reset_index(drop=True)

else:

    df_60 = df_60.drop_duplicates(
        subset=["title"]
    ).reset_index(drop=True)


# ============================================================
# CHECK
# ============================================================

print("\n" + "=" * 60)
print("FINAL 60-BOOK DATASET")
print("=" * 60)

print(
    "Total books:",
    len(df_60)
)

print(
    "Total categories:",
    df_60["category"].nunique()
)

print("\nCategories:")
print(
    df_60["category"].value_counts()
)


# ============================================================
# VALIDATION
# ============================================================

assert len(df_60) == 60

assert df_60["category"].nunique() == 3

for category in TARGET_CATEGORIES:

    assert (
        df_60["category"]
        .eq(category)
        .sum()
        == 20
    )


print("\n✓ 60 BOOKS")
print("✓ 3 CATEGORIES")
print("✓ 20 BOOKS PER CATEGORY")

clean_df = df_60.copy()

clean_df["price_gbp"] = (
    clean_df["price"]
    .astype(str)
    .str.extract(r"(\d+(?:\.\d+)?)")[0]
    .astype(float)
)

rating_map = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

clean_df["rating"] = clean_df["star_rating"].map(rating_map)

clean_df["in_stock"] = clean_df["availability"].astype(str).str.contains(
    "In stock",
    case=False,
    na=False
)

GBP_TO_INR = 105.50

clean_df["price_inr"] = clean_df["price_gbp"] * GBP_TO_INR

clean_df = clean_df[
    [
        "title",
        "price_gbp",
        "price_inr",
        "rating",
        "in_stock",
        "category"
    ]
]

print("Total books:", len(clean_df))
print("Total categories:", clean_df["category"].nunique())

print("\nCategories:")
print(clean_df["category"].value_counts())

display(clean_df.head())

print(clean_df.dtypes)

print(clean_df.isnull().sum())

# Database name
DB_NAME = "books.db"

# Connect to SQLite database
conn = sqlite3.connect(DB_NAME)

# Enable foreign key support
conn.execute("PRAGMA foreign_keys = ON")

cursor = conn.cursor()

# Remove old tables if they already exist
cursor.execute("DROP TABLE IF EXISTS books")
cursor.execute("DROP TABLE IF EXISTS categories")

# Create categories table
cursor.execute("""
CREATE TABLE categories (
    category_id INTEGER PRIMARY KEY AUTOINCREMENT,
    category_name TEXT UNIQUE NOT NULL
)
""")

# Create books table
cursor.execute("""
CREATE TABLE books (
    book_id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    price_gbp REAL,
    price_inr REAL,
    rating INTEGER,
    in_stock INTEGER,
    category_id INTEGER,
    FOREIGN KEY (category_id) REFERENCES categories(category_id)
)
""")

conn.commit()

print("Database and tables created successfully.")

# Get unique categories
categories = clean_df["category"].unique()

for category in categories:
    cursor.execute(
        "INSERT INTO categories (category_name) VALUES (?)",
        (category,)
    )

conn.commit()

# Check categories
category_df = pd.read_sql(
    "SELECT * FROM categories",
    conn
)

display(category_df)

# Create category -> category_id mapping
category_mapping = dict(
    zip(
        category_df["category_name"],
        category_df["category_id"]
    )
)

# Insert books
for _, row in clean_df.iterrows():

    category_id = category_mapping[row["category"]]

    cursor.execute("""
        INSERT INTO books
        (
            title,
            price_gbp,
            price_inr,
            rating,
            in_stock,
            category_id
        )
        VALUES (?, ?, ?, ?, ?, ?)
    """, (
        row["title"],
        row["price_gbp"],
        row["price_inr"],
        row["rating"],
        int(row["in_stock"]),
        category_id
    ))

conn.commit()

print("Books inserted successfully.")

import pandas as pd

result = pd.read_sql(
    "SELECT COUNT(*) AS total_books FROM books",
    conn
)

display(result)

result = pd.read_sql(
    """
    SELECT c.category_name, COUNT(b.book_id) AS book_count
    FROM categories c
    JOIN books b
    ON c.category_id = b.category_id
    GROUP BY c.category_name
    """,
    conn
)

display(result)

query1 = """
SELECT title, price_gbp, rating
FROM books
WHERE rating >= 4
"""

result1 = pd.read_sql(query1, conn)

print("QUERY 1:")
print(query1)

display(result1)

query2 = """
SELECT title, price_gbp, rating
FROM books
ORDER BY price_gbp DESC
LIMIT 10
"""

result2 = pd.read_sql(query2, conn)

print("QUERY 2:")
print(query2)

display(result2)

query3 = """
SELECT DISTINCT category_name
FROM categories
"""

result3 = pd.read_sql(query3, conn)

print("QUERY 3:")
print(query3)

display(result3)

query4 = """
SELECT title, price_gbp, price_inr
FROM books
WHERE price_gbp BETWEEN 20 AND 40
"""

result4 = pd.read_sql(query4, conn)

print("QUERY 4:")
print(query4)

display(result4)

# --------------------------------------------------
# QUERY 5 - IN
# --------------------------------------------------

query5 = """
SELECT title, price_gbp, rating
FROM books
WHERE rating IN (4, 5)
ORDER BY rating DESC
"""

result5 = pd.read_sql(query5, conn)

print("=" * 70)
print("QUERY 5: Books with rating 4 or 5")
print("=" * 70)

print(query5)

display(result5)

# --------------------------------------------------
# SQL QUERY 6
# JOIN
# --------------------------------------------------

join_query = """
SELECT
    b.title,
    c.category_name,
    b.price_gbp,
    b.rating,
    b.in_stock
FROM books b
JOIN categories c
    ON b.category_id = c.category_id
ORDER BY b.rating DESC, b.title
LIMIT 10
"""

join_result = pd.read_sql(join_query, conn)

print("=" * 70)
print("QUERY 6: JOIN - Top 10 Highest-Rated Books")
print("=" * 70)
print(join_query)
display(join_result)

# Read Query 1 result using pd.read_sql()
sql_result_1 = pd.read_sql(query1, conn)

# Read Query 2 result using pd.read_sql()
sql_result_2 = pd.read_sql(query2, conn)

print("Query 1 result using pd.read_sql():")
display(sql_result_1)

print("\nQuery 2 result using pd.read_sql():")
display(sql_result_2)

# Read books table
books_df = pd.read_sql(
    "SELECT * FROM books",
    conn
)

# Read categories table
categories_df = pd.read_sql(
    "SELECT * FROM categories",
    conn
)

print("Books DataFrame:")
display(books_df.head())

print("\nCategories DataFrame:")
display(categories_df)

# --------------------------------------------------
# REPRODUCE SQL JOIN USING pd.merge()
# --------------------------------------------------

pandas_result = pd.merge(
    books_df,
    categories_df,
    on="category_id",
    how="inner"
)

# Select the same columns as SQL JOIN
pandas_result = pandas_result[
    [
        "title",
        "category_name",
        "price_gbp",
        "rating",
        "in_stock"
    ]
]

# Apply the same sorting and LIMIT as SQL
pandas_result = pandas_result.sort_values(
    by=["rating", "title"],
    ascending=[False, True]
).head(10).reset_index(drop=True)

# Reset SQL result index
sql_result = join_result.reset_index(drop=True)

print("SQL JOIN RESULT:")
display(sql_result)

print("\nPANDAS MERGE RESULT:")
display(pandas_result)

# Save cleaned dataset
df.to_csv("cleaned_books.csv", index=False)

# Save SQL query outputs
result1.to_csv("query1_output.csv", index=False)
result2.to_csv("query2_output.csv", index=False)
result3.to_csv("query3_output.csv", index=False)
result4.to_csv("query4_output.csv", index=False)
result5.to_csv("query5_output.csv", index=False)
join_result.to_csv("join_query_output.csv", index=False)

# Save the SQL queries themselves
with open("sql_queries.txt", "w") as f:

    f.write("QUERY 1 - SELECT + WHERE\n")
    f.write(query1)

    f.write("\n\nQUERY 2 - ORDER BY + LIMIT\n")
    f.write(query2)

    f.write("\n\nQUERY 3 - DISTINCT\n")
    f.write(query3)

    f.write("\n\nQUERY 4 - BETWEEN\n")
    f.write(query4)

    f.write("\n\nQUERY 5 - IN\n")
    f.write(query5)

    f.write("\n\nQUERY 6 - JOIN\n")
    f.write(join_query)

print("All outputs saved successfully.")

# ==========================================
# QUERY 6 - SQL JOIN
# ==========================================

query6 = """
SELECT
    b.title,
    b.price_gbp,
    b.price_inr,
    b.rating,
    b.in_stock,
    c.category_name
FROM books AS b
JOIN categories AS c
    ON b.category_id = c.category_id
ORDER BY b.rating DESC
LIMIT 10
"""

result6 = pd.read_sql(query6, conn)

print("QUERY 6 - JOIN")
print(query6)

display(result6)

# ============================================================
# PANDAS MERGE - REPRODUCE THE SQL JOIN
# ============================================================

# Read the two database tables into pandas
books_df = pd.read_sql(
    "SELECT * FROM books",
    conn
)

categories_df = pd.read_sql(
    "SELECT * FROM categories",
    conn
)

print("BOOKS TABLE")
display(books_df.head())

print("CATEGORIES TABLE")
display(categories_df)


# ------------------------------------------------------------
# Perform the JOIN using pandas.merge()
# ------------------------------------------------------------

merge_result = pd.merge(
    books_df,
    categories_df,
    on="category_id",
    how="inner"
)


# ------------------------------------------------------------
# Select exactly the same columns used in SQL JOIN
# ------------------------------------------------------------

merge_result = merge_result[
    [
        "title",
        "category_name",
        "price_gbp",
        "rating",
        "in_stock"
    ]
]


# ------------------------------------------------------------
# Make sure in_stock has the same type as SQL output
# ------------------------------------------------------------

merge_result["in_stock"] = merge_result["in_stock"].astype(int)


# ------------------------------------------------------------
# Apply the SAME sorting as SQL
# ------------------------------------------------------------

merge_result = merge_result.sort_values(
    by=["rating", "title"],
    ascending=[False, True]
)


# ------------------------------------------------------------
# Apply the SAME LIMIT 10 as SQL
# ------------------------------------------------------------

merge_result = merge_result.head(10)


# ------------------------------------------------------------
# Reset index so comparison is fair
# ------------------------------------------------------------

merge_result = merge_result.reset_index(drop=True)


# ------------------------------------------------------------
# Prepare SQL result
# ------------------------------------------------------------

sql_result = join_result[
    [
        "title",
        "category_name",
        "price_gbp",
        "rating",
        "in_stock"
    ]
].copy()

sql_result["in_stock"] = sql_result["in_stock"].astype(int)

sql_result = sql_result.reset_index(drop=True)


# ------------------------------------------------------------
# DISPLAY BOTH RESULTS
# ------------------------------------------------------------

print("=" * 70)
print("SQL JOIN RESULT")
print("=" * 70)

display(sql_result)


print("=" * 70)
print("PANDAS MERGE RESULT")
print("=" * 70)

display(merge_result)

# ============================================================
# STEP 1: SQL JOIN RESULT
# ============================================================

join_query = """
SELECT
    b.title,
    c.category_name,
    b.price_gbp,
    b.rating,
    b.in_stock
FROM books AS b
JOIN categories AS c
    ON b.category_id = c.category_id
ORDER BY b.rating DESC, b.title ASC
LIMIT 10
"""

sql_result = pd.read_sql(join_query, conn)

print("SQL JOIN RESULT")
display(sql_result)

# ============================================================
# STEP 2: PANDAS MERGE RESULT
# ============================================================

# Read both tables
books_df = pd.read_sql(
    "SELECT * FROM books",
    conn
)

categories_df = pd.read_sql(
    "SELECT * FROM categories",
    conn
)

# Perform INNER JOIN using pandas
merge_result = pd.merge(
    books_df,
    categories_df,
    on="category_id",
    how="inner"
)

# Select exactly the same columns as SQL
merge_result = merge_result[
    [
        "title",
        "category_name",
        "price_gbp",
        "rating",
        "in_stock"
    ]
]

# Same sorting as SQL
merge_result = merge_result.sort_values(
    by=["rating", "title"],
    ascending=[False, True]
)

# Same LIMIT 10 as SQL
merge_result = merge_result.head(10)

# Reset index
merge_result = merge_result.reset_index(drop=True)

print("PANDAS MERGE RESULT")
display(merge_result)

# ============================================================
# STEP 3: NORMALIZE BOTH RESULTS
# ============================================================

sql_compare = sql_result.copy()
pandas_compare = merge_result.copy()

# ------------------------------------------------------------
# Make title and category text identical
# ------------------------------------------------------------

sql_compare["title"] = sql_compare["title"].astype(str).str.strip()
pandas_compare["title"] = pandas_compare["title"].astype(str).str.strip()

sql_compare["category_name"] = (
    sql_compare["category_name"].astype(str).str.strip()
)

pandas_compare["category_name"] = (
    pandas_compare["category_name"].astype(str).str.strip()
)

# ------------------------------------------------------------
# Convert price to numeric and round
# ------------------------------------------------------------

sql_compare["price_gbp"] = pd.to_numeric(
    sql_compare["price_gbp"],
    errors="coerce"
).round(2)

pandas_compare["price_gbp"] = pd.to_numeric(
    pandas_compare["price_gbp"],
    errors="coerce"
).round(2)

# ------------------------------------------------------------
# Convert rating to integer
# ------------------------------------------------------------

sql_compare["rating"] = pd.to_numeric(
    sql_compare["rating"],
    errors="coerce"
).astype("Int64")

pandas_compare["rating"] = pd.to_numeric(
    pandas_compare["rating"],
    errors="coerce"
).astype("Int64")

# ------------------------------------------------------------
# Convert in_stock to integer
# SQLite stores BOOLEAN as INTEGER (0/1)
# ------------------------------------------------------------

sql_compare["in_stock"] = (
    pd.to_numeric(
        sql_compare["in_stock"],
        errors="coerce"
    ).astype("Int64")
)

pandas_compare["in_stock"] = (
    pandas_compare["in_stock"]
    .astype(bool)
    .astype(int)
    .astype("Int64")
)

# ------------------------------------------------------------
# Reset index
# ------------------------------------------------------------

sql_compare = sql_compare.reset_index(drop=True)
pandas_compare = pandas_compare.reset_index(drop=True)

print("SQL comparison DataFrame:")
display(sql_compare)

print("Pandas comparison DataFrame:")
display(pandas_compare)

# ============================================================
# STEP 4: FINAL COMPARISON
# ============================================================

comparison_result = sql_compare.equals(pandas_compare)

print("=" * 70)
print("FINAL JOIN VALIDATION")
print("=" * 70)

print("SQL JOIN and pandas merge equivalent:", comparison_result)

# ============================================================
# FINAL OUTPUT FILE GENERATION
# ============================================================

import os
import shutil

print("=" * 70)
print("CREATING PROJECT OUTPUT FILES")
print("=" * 70)


# ------------------------------------------------------------
# 1. CHECK THAT WE HAVE 60 BOOKS
# ------------------------------------------------------------

print("\nNumber of books:", len(df))
print("Number of categories:", df["category"].nunique())

assert len(df) >= 60, "ERROR: Dataset has fewer than 60 books."
assert df["category"].nunique() >= 3, "ERROR: Need at least 3 categories."

print("✓ 60+ books requirement satisfied")
print("✓ 3+ categories requirement satisfied")


# ------------------------------------------------------------
# 2. SAVE CLEANED DATA
# ------------------------------------------------------------

df.to_csv(
    "cleaned_books.csv",
    index=False
)

print("✓ cleaned_books.csv created")


# ------------------------------------------------------------
# 3. SAVE SQLITE DATABASE
# ------------------------------------------------------------

# Make sure all database changes are committed
conn.commit()

print("✓ books.db is ready")


# ------------------------------------------------------------
# 4. CREATE SQL QUERIES
# ------------------------------------------------------------

query1 = """
SELECT title, price_gbp, rating
FROM books
WHERE rating >= 4
"""

query2 = """
SELECT title, price_gbp
FROM books
ORDER BY price_gbp DESC
LIMIT 10
"""

query3 = """
SELECT DISTINCT rating
FROM books
ORDER BY rating
"""

query4 = """
SELECT title, price_gbp
FROM books
WHERE price_gbp BETWEEN 10 AND 30
"""

query5 = """
SELECT title, category_id, rating
FROM books
WHERE rating IN (4, 5)
"""

join_query = """
SELECT
    b.title,
    c.category_name,
    b.price_gbp,
    b.rating,
    b.in_stock
FROM books b
JOIN categories c
    ON b.category_id = c.category_id
ORDER BY b.rating DESC, b.title
LIMIT 10
"""


# ------------------------------------------------------------
# 5. EXECUTE SQL QUERIES AND SAVE THEIR OUTPUT
# ------------------------------------------------------------

result1 = pd.read_sql(query1, conn)
result1.to_csv("query1_output.csv", index=False)

result2 = pd.read_sql(query2, conn)
result2.to_csv("query2_output.csv", index=False)

result3 = pd.read_sql(query3, conn)
result3.to_csv("query3_output.csv", index=False)

result4 = pd.read_sql(query4, conn)
result4.to_csv("query4_output.csv", index=False)

result5 = pd.read_sql(query5, conn)
result5.to_csv("query5_output.csv", index=False)

join_result = pd.read_sql(join_query, conn)
join_result.to_csv("join_query_output.csv", index=False)

print("✓ query1_output.csv created")
print("✓ query2_output.csv created")
print("✓ query3_output.csv created")
print("✓ query4_output.csv created")
print("✓ query5_output.csv created")
print("✓ join_query_output.csv created")


# ------------------------------------------------------------
# 6. SAVE SQL QUERY STRINGS
# ------------------------------------------------------------

with open("sql_queries.txt", "w") as f:

    f.write("=" * 70 + "\n")
    f.write("QUERY 1 - SELECT + WHERE\n")
    f.write("=" * 70 + "\n")
    f.write(query1)

    f.write("\n\n")
    f.write("=" * 70 + "\n")
    f.write("QUERY 2 - ORDER BY + LIMIT\n")
    f.write("=" * 70 + "\n")
    f.write(query2)

    f.write("\n\n")
    f.write("=" * 70 + "\n")
    f.write("QUERY 3 - DISTINCT\n")
    f.write("=" * 70 + "\n")
    f.write(query3)

    f.write("\n\n")
    f.write("=" * 70 + "\n")
    f.write("QUERY 4 - BETWEEN\n")
    f.write("=" * 70 + "\n")
    f.write(query4)

    f.write("\n\n")
    f.write("=" * 70 + "\n")
    f.write("QUERY 5 - IN\n")
    f.write("=" * 70 + "\n")
    f.write(query5)

    f.write("\n\n")
    f.write("=" * 70 + "\n")
    f.write("QUERY 6 - JOIN\n")
    f.write("=" * 70 + "\n")
    f.write(join_query)

print("✓ sql_queries.txt created")


# ------------------------------------------------------------
# 7. VERIFY SQL JOIN VS PANDAS MERGE
# ------------------------------------------------------------

books_df = pd.read_sql(
    "SELECT * FROM books",
    conn
)

categories_df = pd.read_sql(
    "SELECT * FROM categories",
    conn
)

pandas_result = pd.merge(
    books_df,
    categories_df,
    on="category_id",
    how="inner"
)

pandas_result = pandas_result[
    [
        "title",
        "category_name",
        "price_gbp",
        "rating",
        "in_stock"
    ]
]

pandas_result = pandas_result.sort_values(
    by=["rating", "title"],
    ascending=[False, True]
).head(10).reset_index(drop=True)

sql_result = join_result.reset_index(drop=True)

print("\nSQL JOIN vs pandas merge:")
print(sql_result.equals(pandas_result))

assert sql_result.equals(pandas_result), \
    "ERROR: SQL JOIN and pandas merge results do not match."

print("✓ SQL JOIN and pandas merge are equivalent")


# ------------------------------------------------------------
# 8. FINAL FILE LIST
# ------------------------------------------------------------

required_files = [
    "books.db",
    "cleaned_books.csv",
    "sql_queries.txt",
    "query1_output.csv",
    "query2_output.csv",
    "query3_output.csv",
    "query4_output.csv",
    "query5_output.csv",
    "join_query_output.csv"
]

print("\n" + "=" * 70)
print("FINAL FILE CHECK")
print("=" * 70)

for file_name in required_files:

    if os.path.exists(file_name):
        size = os.path.getsize(file_name)

        print(f"✓ {file_name} ({size} bytes)")

    else:
        print(f"✗ {file_name} NOT FOUND")


print("\n" + "=" * 70)
print("ALL OUTPUT FILES GENERATED")
print("=" * 70)

"""Create README.md"""

# Commented out IPython magic to ensure Python compatibility.
# 
# %%writefile README.md
# %%writefile README.md
# 
# # Data Pipeline
# 
# ## Overview
# 
# This module implements an end-to-end data engineering pipeline for scraping, cleaning, converting, storing, and querying book catalogue data.
# 
# The data is collected from Books to Scrape, a public website designed for scraping practice.
# 
# ## Data Collection
# 
# The pipeline scrapes the first five pages of the All Products catalogue.
# 
# Each page contains approximately 20 books, resulting in approximately 100 scraped books.
# 
# From the scraped dataset, 60 books are selected for the project.
# 
# The selected dataset contains at least three different book categories.
# 
# The scraping process is automated and does not require manual copy-pasting of data.
# 
# ## Libraries Used
# 
# The following Python libraries are used:
# 
# - requests
# - BeautifulSoup
# - pandas
# - sqlite3
# 
# ## Data Cleaning
# 
# The following transformations are applied:
# 
# - The pound symbol is removed from the price field.
# - The cleaned price is converted to a float column named `price_gbp`.
# - Star ratings such as One, Two, Three, Four, and Five are converted to integers from 1 to 5.
# - Availability text is converted into a boolean column named `in_stock`.
# - If a numeric field fails to parse, the median value is used for imputation.
# 
# ## Currency Conversion
# 
# The project uses the required fixed project-defined conversion rate:
# 
# **1 GBP = 105.50 INR**
# 
# The INR price is calculated as:
# 
# ```text
# price_inr = price_gbp * 105.50

"""Create requirements.txt"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# requests
# beautifulsoup4
# pandas

"""Create sql_queries.txt in Colab"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile sql_queries.txt
# 
# QUERY 1 - SELECT and WHERE
# ==========================
# 
# SELECT *
# FROM books
# WHERE rating >= 4;
# 
# 
# QUERY 2 - ORDER BY
# ==================
# 
# SELECT title, price_gbp
# FROM books
# ORDER BY price_gbp DESC;
# 
# 
# QUERY 3 - LIMIT
# ===============
# 
# SELECT title, price_gbp
# FROM books
# ORDER BY price_gbp DESC
# LIMIT 10;
# 
# 
# QUERY 4 - DISTINCT
# ==================
# 
# SELECT DISTINCT rating
# FROM books;
# 
# 
# QUERY 5 - BETWEEN and IN
# ========================
# 
# SELECT *
# FROM books
# WHERE price_gbp BETWEEN 20 AND 40
# AND rating IN (4, 5);
# 
# 
# QUERY 6 - JOIN
# ==============
# 
# SELECT
#     b.title,
#     b.price_gbp,
#     c.category_name
# FROM books b
# JOIN categories c
#     ON b.category_id = c.category_id;

!cat sql_queries.txt



